# Azure DevOps Pipeline — Api1 (Products Service)
# Triggers on changes to src/Api1/**

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/Api1/**
      - infra/k8s/api1-deployment.yaml
      - pipelines/templates/build-push-deploy.yml

pr:
  branches:
    include:
      - main
      - develop
  paths:
    include:
      - src/Api1/**


variables:
  - group: poc-common-vars   # variable group defined in Azure DevOps Library

stages:
  - template: templates/build-push-deploy.yml
    parameters:
      apiName: api1
      projectPath: src/Api1
      k8sManifest: infra/k8s/api1-deployment.yaml
